name: ppd599

channels:
  - conda-forge

dependencies:
  - beautifulsoup4
  - black
  - cartopy
  - cenpy
  - conda
  - contextily
  - dill
  - flake8
  - folium
  - geopandas
  - isort
  - jupyterlab
  - mapclassify
  - osmnx=1.2.3
  - nbqa
  - pandana
  - pandas
  - pysal
  - python=3.10.*
  - rasterio
  - rtree
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  # bokeh
  # datashader
  # holoviews
  # keras
  # nltk
  # psycopg2
  # pydeck
  # urbanaccess
